### ISSUE TITLE
Common npm scripts along with configuration packages

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-config#10]
Currently there is a lot of copy-and-paste of npm scripts associated with the different tasks like `test`, `format` and the like, see e.g. in [this PR](https://github.com/ethereumjs/ethereumjs-account/pull/27/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) on the Account library.

If there is a clean solution for that we should add these script commands here. Commands should be associated with the respective config package type release (e.g. `format:*` scripts distributed within the `ethereumjs-config-prettier` package) to ensure that commands remain compatible with the tool version targeted by configuration.

Issue should be targeted relatively quickly so that we can integrate this early on within follow-up `TypeScript` rewrites and don't have to update too much already transitioned libraries.

**Comment by holgerd77** [comment]
Additional note: this should also help keep directory/repository structures unified as some side effect as well as have some unified evolvement/improvement of the script commands itself, e.g. by adding new CL options, improving wildcards on paths, stuff like that.

**Comment by krzkaczor** [comment]
How do we want to achieve this? What's the plan? @holgerd77 @whymarrh

**Comment by holgerd77** [comment]
I think @whymarrh had some ideas on this, he once mentioned on Gitter.

Additional note: this should also remain so flexible that one COULD use an own script to depart from the standard if necessary.

**Comment by holgerd77** [comment]
Maybe with some Node `bin` CLI script approach: https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e

?

**Comment by whymarrh** [comment]
Yup, a CLI would work (similar to `react-scripts`). We could have options/flags to allow consumers to change the behaviour if needed, achieving the flexibility you're talking about above @holgerd77. We could also have a package with some Bash scripts (which is the _simplest_ solution) but that would only be a good idea if people like writing Bash. 😄

**Comment by holgerd77** [comment]
Solved by #13.
