### ISSUE TITLE
TSLint warning on no-console and no-commented-code

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-config#14]
While I agree that `no-console` and `no-commented-code` are net-positive, they're a bit annoying during development :( Can we set them to `warning` level rather than `error`?

**Comment by holgerd77** [comment]
Yes, would also agree on this, @krzkaczor also gave thumbs-up, so you can open a PR if you want.

**Comment by s1na** [comment]
@holgerd77 seems like I don't have write access, should I fork the repo?

**Comment by holgerd77** [comment]
No, wait...

**Comment by holgerd77** [comment]
Was some not intended team setting, have update this, should work now.

**Comment by s1na** [comment]
Implemented via #15.
