### ISSUE TITLE
TSLint not invoked on lint cli

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-config#19]
It has happened a few times for me that running `npm run lint` returns no error, but running `npm run tslint` does return errors, which is strange given that `lint` runs `tslint` internally.

**Comment by holgerd77** [comment]
I would generally find it good if these lint and prettier commands would be a bit more verbose. A bit too much auto-magic for my taste. 😋

**Comment by holgerd77** [comment]
Might this be related to the problems in the ``merkle-patricia-tree`` library addressed [here](https://github.com/ethereumjs/merkle-patricia-tree/pull/83#pullrequestreview-209011238)?

**Comment by s1na** [comment]
Hm, I think that might be it! TSLint probably ignores files in `.gitignore`!

**Comment by holgerd77** [comment]
Ok, think I will close this here for now, can always reopen if necessary. 😄

**Comment by s1na** [comment]
This issue still persists, and is not due to `.gitignore`. `npm run lint` is not really invoking tslint.

**Comment by alcuadrado** [comment]
Where do you see this issue? In which projects?

**Comment by s1na** [comment]
I noticed in while working on [turbo-token](https://github.com/s1na/turbo-token), but just tested in VM and it's the same.

**Comment by krzkaczor** [comment]
Can u provide a CI build link?

**Comment by s1na** [comment]
From https://circleci.com/gh/ethereumjs/ethereumjs-vm/7322:

```sh
#!/bin/bash -eo pipefail
npm run lint

> ethereumjs-vm@4.1.0 lint /home/circleci/project/ethereumjs-vm
> ethereumjs-config-lint

+ exec npm run format

> ethereumjs-vm@4.1.0 format /home/circleci/project/ethereumjs-vm
> ethereumjs-config-format

+ exec prettier --list-different **/*.{ts,json,md}
```
