### ISSUE TITLE
Exporting sources and declarationmaps

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-config#21]
(I'm not sure if this is the right repo to create this issue, feel free to move it)

I found myself moving from my text editor to a Github tab like [this one](https://github.com/ethereumjs/ethereumjs-util/blob/v6.1.0/src/index.ts) every time I have a doubt about some of the ethereumjs libraries and I have to read its implementation. 

This could be much more practical if sources, ~~sourcemaps~~ and declaration maps were also exported in the npm packages. Currently only the compiled js, source maps, and the declaration files are exported.

Exporting those files can also be used to generate better stack traces (e.g. with `source-map-support`).

The only drawback I see is that compilations may take slightly more and packages will use more space. 

IMO it's a change worth doing. If you agree, I can start by implementing it in https://github.com/ethereumjs/ethereumjs-tx/pull/145.

EDIT: Sourcemaps are generated and exported. Without the sources they are not useful.

**Comment by holgerd77** [comment]
Hmm, this would more-or-less double the package size if I'm not missing something.

Also, npm packages are not mainly for internal development but for users of the libraries.

**Comment by alcuadrado** [comment]
> Hmm, this would more-or-less double the package size if I'm not missing something.

Yes, that's right.
 
> Also, npm packages are not mainly for internal development but for users of the libraries.

I use ethereumjs, mostly ethereumjs-util and ethereumjs-tx, in other projects and I find myself in the same situation there.

I think it would be even more valuable for users, as they may not be that familiar with the libs' internals. For example, if you use an IDE/editor go-to-definition now it takes to the `.d.ts`. If these files get exported it would take you to the sources.

**Comment by krzkaczor** [comment]
IMO package size itself doesn't really matter, what's important is the size of a bundled code in the final app which won't change. 

That being said I think shipping source code is not a good idea — if you want them you can link packages locally (`yarn link`). 

 declarations `d.ts` should be part of packages aren't they now? Or did I misunderstand that part?

**Comment by holgerd77** [comment]
Hi @krzkaczor, thanks for an additional statement here, this is really valuable since the point seems somewhat controversial. Can you give an argument for the "not a good idea" part? Otherwise reasoning here remains intransparent. Thanks! 😀

**Comment by krzkaczor** [comment]
Heheh yes :D Sooo basically I never really saw any package doing this, shipping original sources. 

I always try to ship minimal packages and this seems to be totally redundant. As you mentioned, this should be for consumers, not developers and if you need original source I guess just the link package locally.  dts files are useful for consumers so they should be part of the package.

**Comment by alcuadrado** [comment]
> IMO package size itself doesn't really matter, what's important is the size of a bundled code in the final app which won't change.

Completely agree with this.

> declarations `d.ts` should be part of packages aren't they now? Or did I misunderstand that part?

Yes, now packages are shipping with `.js`, `.js.map` and `.d.ts`.

> As you mentioned, this should be for consumers, not developers and if you need original source I guess just the link package locally. dts files are useful for consumers so they should be part of the package.

IMO sources are valuable for consumers. They are the ultimate documentation.

I think this isn't common yet in TS packages because they are distributed through npm, which was designed for javascript. Other ecosystems (e.g. Java and many linux flavors) have independent packages for compilation outputs, docs, and sources.

This is an interesting thread about this topic: https://twitter.com/bterlson/status/1053644764988366850

**Comment by krzkaczor** [comment]
@alcuadrado maybe you're right regarding shipping sources. I never did this but it looks like it brings some value. I somehow got used to "compiled" code 🤷‍♂️

**Comment by holgerd77** [comment]
I wouldn't want to change this overnight, since this is somewhat too big of a change if applied to all libraries and also might have side effects. So let this sink in a bit more, not totally against it.

**Comment by holgerd77** [comment]
@alcuadrado Linked twitter thread is definitely interesting.

**Comment by alcuadrado** [comment]
Just a data point:

I just submitted [this PR to Buidler](https://github.com/nomiclabs/buidler/pull/251/files). It's a super simple change, it just adds a missing call to [`bufferToHex`](https://github.com/ethereumjs/ethereumjs-util/blob/8ffe697fafb33cefc7b7ec01c11e3a7da787fe0e/src/bytes.ts#L108).

It took me some extra minutes because its documentation is not clear if it adds the `0x` prefix or not. Reading [its source code](https://github.com/ethereumjs/ethereumjs-util/blob/8ffe697fafb33cefc7b7ec01c11e3a7da787fe0e/src/bytes.ts#L111) made immediately clear that it does prepend `0x`.

I know that this is probably a documentation issue, but small things like this are always present. 

Having the ability to jump to the right version of the code without living the editor is very valuable.

**Comment by krzkaczor** [comment]
Side note: `Opaque types` are perfect to accomplish this with TS. https://github.com/krzkaczor/ts-essentials#opaque-types

**Comment by nivida** [comment]
As mentioned in https://github.com/ethereum/web3.js/pull/3160 do I add here my latest foundings about the source map warnings I'm seeing with the bundler Parcel.

As I understand the warning from the attached screenshot does the published source maps point on the actual source files instead of the published ``dist`` files. We can add those source files to the published package or we correct the URLs in the source maps to point on the ``dist`` files instead of the TS source files.

<img width="1283" alt="Bildschirmfoto 2019-11-13 um 09 51 23" src="https://user-images.githubusercontent.com/1699173/68849105-c5854b00-06d1-11ea-9ba4-f876946f83ab.png">

**Comment by alcuadrado** [comment]
I don't follow what you mean by pointing them to `dist` files, can you clarify? We only have compiled files there.

**Comment by nivida** [comment]
For example the ``ethereumjs-util`` source map does have the following sources array:
```
"sources":["../src/index.ts"]
``` 

Those defined sources should probably point on the compiled/transformed dist files:
```
"sources":["../dist/index.js"]
```

**Comment by alcuadrado** [comment]
I don't get it, why would you make a compilation output's source map point to itself? That would be exactly the same as not providing a source map.

Having a source map pointed to a missed file at least give you source-mapped stack traces.

**Comment by nivida** [comment]
> I don't get it, why would you make a compilation output's source map point to itself? That would be exactly the same as not providing a source map.

As said are there two options. We upload the TS source files as well or our source maps do point on the transformed ``dist`` files we use. I think pointing on the related JS dist files does give us the same result as we would upload those TS sources.

**Comment by alcuadrado** [comment]
Sorry, but I don't follow it. How does it give us the same result? Do you mean using inline source maps?
