### ISSUE TITLE
Coveralls reporting not working

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-config#22]
Discovered during a check on an ``nyc`` version update PR on the blockchain library that coveralls reporting is currently not working when using the scripts from the config library:
https://github.com/ethereumjs/ethereumjs-blockchain/pull/97

Did some tests and can confirm that removing the all ``exec`` statements from both the ``coverage`` and the ``coveralls`` command fixes this.

**Comment by ryanio** [comment]
I suggest we remove `coveralls` functionality in  this repo now that we can simply push to coveralls (or codecov, etc.) with GitHub Actions like so:

https://github.com/ethereumjs/ethereumjs-util/blob/3bbc948a1887df5f10fb0ebc3f07b7b9f774302c/.github/workflows/build.yml#L27-L30

**Comment by holgerd77** [comment]
coveralls: yes, makes sense
coverage: not 100% sure but have a tendency to remove as well. That would mean we kill the whole package?

**Comment by ryanio** [comment]
Well, I think we can keep the nyc config
