### ISSUE TITLE
Update libraries to handle monorepo consumers

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-config#24]
We'll now start on consolidating some repos by integrating in a monorepo, first integration will be several libraries (blockchain, block, tx, account) within the VM repository, see https://github.com/ethereumjs/ethereumjs-vm/issues/561 for reference.

The libraries here have to be updated so that the configuration defined here is consumable by a monorepo-style repository.

**Comment by evertonfraga** [comment]
Hi @holgerd77, any ideas how could we improve it with the monorepo setup?

**Comment by holgerd77** [comment]
I actually wrote this from a perspective that I thought it would be more problematic to use the current setup within the monorepo context, which was to some extend a wrong assumption.

I would therefore close here, this issue or a similar respectively more specific one can be re-opened once someone has ideas on how to consolidate more (not sure if this is necessary though).

**Comment by evertonfraga** [comment]
Thanks!
