### ISSUE TITLE
Minimal CI/tests to check configuration integrity

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-config#3]
We should add some minimal CI for PRs to at least check the integrity of configuration. Simple better-than-nothing solution would be to just read/load the respective ``JSON`` files with JavaScript/TypeScript and make sure there is no error thrown on the way.

**Comment by evertonfraga** [comment]
This is very important. Testing these packages manually is far from ideal.

Let me outline what I have in mind. If y'all agree, I can implement when priorities align.

We can have some mock repositories under a `tests` folder, so we can run the scripts against them and validate the output with not-so-strict checks, initially. The idea is to first test the script execution, then any specific rule (_e.g: tabs vs. spaces ESLint_).

File structure: 
```
packages/lint
  tests
    + run.sh
    + mock-repo
      package.json (with @ethereumjs/config-lint dep and scripts)
      main.ts (with lint failures)
```

A super simple test runner:
```sh
# run.sh

cd tests/mock-repo
npm run lint
# > no errors, that's already something
validate() # should display at least 1 available fix

npm run lint:fix
validate() # should have written to given files
```

**Comment by holgerd77** [comment]
@evertonfraga That's brilliant, really nice idea! 😄
