### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-config#31]
@gabrocheleau tried to run `npm run lint:fix` on Merkle Patricia Tree, but got this error. 

This is most likely an issue due to the lack of windows support. 

![image](https://user-images.githubusercontent.com/47108/85287763-beda6580-b462-11ea-8eac-24a4db951de4.png)

**Comment by ryanio** [comment]
@evertonfraga is this fixed/closable now with the config 2.0 scripts?

**Comment by evertonfraga** [comment]
No. To enable windows, we should make the npm scripts execution cross-platform. Like getting rid of shell scripts, replacing them by executable JS files.

**Comment by rumkin** [comment]
+1 on getting rid of shell scripts.
