### ISSUE TITLE
`realpath` shell utility used by lint scripts is missing on Mac OSX 

### ISSUE THREAD

**Issue by cgewecke** [ethereumjs/ethereumjs-config#41]
Running `lint` on OSX throws an error like this:
```
@ethereumjs/tx: /ethereumjs-vm/.../.bin/ethereumjs-config-lint: line 26: realpath: command not found
```

It can be installed on OSX with
```
brew install coreutils
```

The utility is invoked in the scripts as below...
https://github.com/ethereumjs/ethereumjs-config/blob/b3b59095c47db6c7e74c3368758f4e372e9b34a7/packages/lint/cli/lint-fix.sh#L26

From discord discussion, should we...?
+ add a test for `realpath` existence in the lint scripts and warn user if not found (@ryanio's 💡 )
+ add warning in README here
+ add warning in README in monorepo (or, optionally - everywhere)

**Comment by holgerd77** [comment]
Is there any alternative to `realpath` which is more widely available?

**Comment by cgewecke** [comment]
There is script and relevant stack-overflow links suggested in [this Github issue comment][1] where they're facing the same problem.

@holgerd77 Do you think something like that is worth trying?

[1]: https://github.com/whatwg/html-build/issues/90#issuecomment-235960102

**Comment by holgerd77** [comment]
@cgewecke hmm, no high priority atm I would say at least since we only use internally and now everyone is aware.

**Comment by rumkin** [comment]
I faced this issue. While I can handle it, I think it would be better to refuse to use bash scripts in the project. It's not reliable and hard to support across different environments. I've met such issues before on other projects and I think it's better to write scripts with something more developer-friendly. IMO it should be JS. But other solutions with cross-platform support should play well here.
