### ISSUE TITLE
Enforce a convention in module import order

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-config#43]
I am opening this issue as a suggestion to add an [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) rule to our base lint config.

I am liking a lot of the [rules](https://github.com/benmosher/eslint-plugin-import#rules) from this plugin, so we can consider adding them all with:

```yaml
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
```

**Comment by rumkin** [comment]
I'd suggest to split imports into three groups followed in the next order:

* System packages
* External dependencies
* Internal Dependencies

It helps me to keep things organized and not to bring import block into a mess. Sometimes intensive usage of system packages highlights a problem with too tight couple of a library and Node.js.

**Comment by holgerd77** [comment]
Yeah, love this, especially since it seems we can keep the import semantic ordering as @rumkin described. Just as a mention, this will likely be some substantial work on an upgrade, adding all these in-between comment lines. But so be it. 🤷‍♂️

**Comment by rumkin** [comment]
@holgerd77 This is autofixable rule. It groups imports and inserts empty lines between groups. So everything should go smooth.

**Comment by ryanio** [comment]
hmm I didn't notice this `newlines-between` option, I would prefer no newlines between groups, just a proper ordering would be great to me.

**Comment by holgerd77** [comment]
Ah, somewhat confusing maybe from my side: I didn't want to make a case for the comment lines - I would actually prefer the version without them. I just assumed that we just have to add these manually for the linting option to work properly. If this is not the case, even better.
